// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Screen1_Image1;
extern lv_obj_t * ui_Button2;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_flaszka_png);    // assets\flaszka.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
