// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.3
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_COMP_H
#define _SQUARELINE_PROJECT_UI_COMP_H

#ifdef __cplusplus
extern "C" {
#endif


lv_obj_t * ui_comp_get_child(lv_obj_t * comp, uint32_t child_idx);
extern uint32_t LV_EVENT_GET_COMP_CHILD;

// COMPONENT Screen1 Image1
#define UI_COMP_SCREEN1_IMAGE1_SCREEN1_IMAGE1 0
#define _UI_COMP_SCREEN1_IMAGE1_NUM 1
lv_obj_t * ui_Screen1_Image1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
